# ##### SUCCESS #####

# ##### ERROR #####
CODE_ERROR_INTERNAL_LIBRARY = "ERROR_INTERNAL_LIBRARY"

# ##### NOT #####

# ##### NOT_VALID #####
CODE_NOT_VALID_INTEGER = "NOT_VALID_INTEGER"
CODE_NOT_VALID_STATUS_TASK = "NOT_VALID_STATUS_TASK"
CODE_NOT_VALID_PROPERTIES_TASK = "NOT_VALID_PROPERTIES_TASK"
CODE_NOT_VALID_TASK = "NOT_VALID_TASK"

# ##### NOT_EXISTS #####
CODE_NOT_EXISTS_TASK = "NOT_EXISTS_TASK"

# ##### ALREADY_EXISTS #####
CODE_ALREADY_EXISTS_TASK = "ALREADY_EXISTS_TASK"

# ##### NOT_FOUND #####
CODE_NOT_FOUND_TASK = "NOT_FOUND_TASK"
